# Generated by Django 5.2.6 on 2025-09-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_session_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PND", "Pending"),
                    ("P", "Paid"),
                    ("CNC", "Cancelled"),
                    ("EXP", "Expired"),
                ],
                default="PND",
                max_length=3,
            ),
        ),
    ]
