# Generated by Django 5.2.6 on 2025-09-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Cancelled", "Cancelled"),
                    ("Expired", "Expired"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("Payment", "Payment"), ("Fine", "Fine")],
                default="Payment",
                max_length=10,
            ),
        ),
    ]
