# Generated by Django 5.2.6 on 2025-09-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_unique_book"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ("title",)},
        ),
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("Hard", "Hard"), ("Soft", "Soft")],
                default="Soft",
                max_length=5,
            ),
        ),
    ]
