# Generated by Django 5.2.6 on 2025-09-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="book_id",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="borrowing",
            old_name="user_id",
            new_name="user",
        ),
    ]
