# Generated by Django 5.2.6 on 2025-09-23 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0004_alter_borrowing_actual_return_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ("borrow_date",)},
        ),
    ]
