# Generated by Django 5.2.6 on 2025-09-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0006_alter_borrowing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ("-borrow_date", "-id")},
        ),
    ]
